#!/usr/bin/env bash
# install and configure haproxy.

sudo apt-get -y install --no-install-recommends software-properties-common
sudo ass-apt-repository -y ppa:vbernat/haproxy-2.0
sudo apt-get -y update
sudo apt-get -y update
sudo apt-get -y install haproxy=2.0\*

cat >> /etc/haproxy/haproxy.cfg << EOF
frontend Local_Server
        bind *:80
  	mode http
	default_backend Web_Servers
backend Web_Servers
	balance roundrobin
	mode http
	server web-01 35.175.179.143:80 check
	server web-02 34.203.200.250:80 check
EOF

sudo service haproxy restart
